# Generated by Django 3.2.4 on 2021-07-03 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210702_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
