# Generated by Django 3.2.4 on 2021-07-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_watcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='watcher',
            new_name='watchers',
        ),
    ]
