# Generated by Django 3.2.4 on 2021-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='closingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
