# Generated by Django 3.2.4 on 2021-07-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_closingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winnerBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
